# Site settings
title: Galaxy Training
description: Collection of training resources for Galaxy courses - Community Site
github_username: ELIXIR-ITA-training
github_repo: Galaxy
galaxy_url: http://90.147.170.113
pages_url: https://ELIXIR-ITA-training.github.io/Galaxy
github_url: https://github.com/ELIXIR-ITA-training/Galaxy

# Build settings
markdown: kramdown
